- name: disable default nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: disable default nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present